<%@ Page Title="" Language="C#" MasterPageFile="~/SMS.Master" AutoEventWireup="true" CodeBehind="AdminPage.aspx.cs" Inherits="Student_Managment_System.AdminPage" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>This is Admin Page .. !</h1>
    <hr />
    <asp:DropDownList ID="DropDownList1" runat="server">
        <asp:ListItem>Coursetable</asp:ListItem>
        <asp:ListItem>student</asp:ListItem>
        <asp:ListItem>tutor</asp:ListItem>
    </asp:DropDownList>
    <asp:Button ID="ButSubmit" runat="server" Text="Submit" OnClick="ButSubmit_Click" />
    <asp:GridView ID="GdCourse" runat="server" DataKeyNames="Cid" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" OnRowCancelingEdit="GdCourse_RowCancelingEdit" OnRowDeleting="GdCourse_RowDeleting" OnRowEditing="GdCourse_RowEditing" OnRowUpdating="GdCourse_RowUpdating"></asp:GridView>
    <asp:GridView ID="GdStudent" runat="server" DataKeyNames="Stid" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" OnRowCancelingEdit="GdStudent_RowCancelingEdit" OnRowDeleting="GdStudent_RowDeleting" OnRowEditing="GdStudent_RowEditing" OnRowUpdating="GdStudent_RowUpdating"></asp:GridView>
    <asp:GridView ID="GdTutor" runat="server" DataKeyNames="Tid" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" OnRowCancelingEdit="GdTutor_RowCancelingEdit" OnRowDeleting="GdTutor_RowDeleting" OnRowEditing="GdTutor_RowEditing" OnRowUpdating="GdTutor_RowUpdating"></asp:GridView>
</asp:Content>
